1. [Ingestion](https://harvi14.github.io/DataScienceProjects/Ingestion_261.html)
2. [EDA](https://harvi14.github.io/DataScienceProjects/EDA_261.html)
3. [Modeling](https://harvi14.github.io/DataScienceProjects/Model_261.html)
4. [CrossValidation](https://harvi14.github.io/DataScienceProjects/CV_261.html)
5. [Report](https://harvi14.github.io/DataScienceProjects/Report_261.html)
